package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.ClassType;
import com.happydriving.rockets.server.entity.ClassTypeExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface ClassTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int countByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int deleteByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    @Delete({
        "delete from class_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    @Insert({
        "insert into class_type (id, created_at, ",
        "updated_at, class_type)",
        "values (#{id,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{classType,jdbcType=VARCHAR})"
    })
    int insert(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int insertSelective(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    List<ClassType> selectByExample(ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, created_at, updated_at, class_type",
        "from class_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ClassType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ClassType record, @Param("example") ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ClassType record, @Param("example") ClassTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClassType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_type
     *
     * @mbggenerated
     */
    @Update({
        "update class_type",
        "set created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP},",
          "class_type = #{classType,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ClassType record);
}