package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.CoachUploadPhoto;
import com.happydriving.rockets.server.entity.CoachUploadPhotoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CoachUploadPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_upload_photo
     *
     * @mbggenerated
     */
    int countByExample(CoachUploadPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_upload_photo
     *
     * @mbggenerated
     */
    int deleteByExample(CoachUploadPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_upload_photo
     *
     * @mbggenerated
     */
    @Delete({
            "delete from coach_upload_photo",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_upload_photo
     *
     * @mbggenerated
     */
    @Insert({
            "insert into coach_upload_photo (id, coach_id, ",
            "upload_photo, created_at, ",
            "updated_at)",
            "values (#{id,jdbcType=INTEGER}, #{coachId,jdbcType=INTEGER}, ",
            "#{uploadPhoto,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
            "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(CoachUploadPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_upload_photo
     *
     * @mbggenerated
     */
    int insertSelective(CoachUploadPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_upload_photo
     *
     * @mbggenerated
     */
    List<CoachUploadPhoto> selectByExample(CoachUploadPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_upload_photo
     *
     * @mbggenerated
     */
    @Select({
            "select",
            "id, coach_id, upload_photo, created_at, updated_at",
            "from coach_upload_photo",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    CoachUploadPhoto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_upload_photo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoachUploadPhoto record, @Param("example") CoachUploadPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_upload_photo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoachUploadPhoto record, @Param("example") CoachUploadPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_upload_photo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoachUploadPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_upload_photo
     *
     * @mbggenerated
     */
    @Update({
            "update coach_upload_photo",
            "set coach_id = #{coachId,jdbcType=INTEGER},",
            "upload_photo = #{uploadPhoto,jdbcType=VARCHAR},",
            "created_at = #{createdAt,jdbcType=TIMESTAMP},",
            "updated_at = #{updatedAt,jdbcType=TIMESTAMP}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CoachUploadPhoto record);
}