package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.CoachCertificatePhoto;
import com.happydriving.rockets.server.entity.CoachCertificatePhotoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CoachCertificatePhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_certificate_photo
     *
     * @mbggenerated
     */
    int countByExample(CoachCertificatePhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_certificate_photo
     *
     * @mbggenerated
     */
    int deleteByExample(CoachCertificatePhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_certificate_photo
     *
     * @mbggenerated
     */
    @Delete({
        "delete from coach_certificate_photo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_certificate_photo
     *
     * @mbggenerated
     */
    @Insert({
        "insert into coach_certificate_photo (id, coach_id, ",
        "personal_photo, id_card_positive_photo, ",
        "id_card_negative_photo, driving_licence_photo, ",
        "car_running_photo, coach_certificate_photo, ",
        "operation_certificate_photo, created_at, ",
        "updated_at)",
        "values (#{id,jdbcType=INTEGER}, #{coachId,jdbcType=INTEGER}, ",
        "#{personalPhoto,jdbcType=VARCHAR}, #{idCardPositivePhoto,jdbcType=VARCHAR}, ",
        "#{idCardNegativePhoto,jdbcType=VARCHAR}, #{drivingLicencePhoto,jdbcType=VARCHAR}, ",
        "#{carRunningPhoto,jdbcType=VARCHAR}, #{coachCertificatePhoto,jdbcType=VARCHAR}, ",
        "#{operationCertificatePhoto,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(CoachCertificatePhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_certificate_photo
     *
     * @mbggenerated
     */
    int insertSelective(CoachCertificatePhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_certificate_photo
     *
     * @mbggenerated
     */
    List<CoachCertificatePhoto> selectByExample(CoachCertificatePhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_certificate_photo
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, coach_id, personal_photo, id_card_positive_photo, id_card_negative_photo, ",
        "driving_licence_photo, car_running_photo, coach_certificate_photo, operation_certificate_photo, ",
        "created_at, updated_at",
        "from coach_certificate_photo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    CoachCertificatePhoto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_certificate_photo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoachCertificatePhoto record, @Param("example") CoachCertificatePhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_certificate_photo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoachCertificatePhoto record, @Param("example") CoachCertificatePhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_certificate_photo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoachCertificatePhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_certificate_photo
     *
     * @mbggenerated
     */
    @Update({
        "update coach_certificate_photo",
        "set coach_id = #{coachId,jdbcType=INTEGER},",
          "personal_photo = #{personalPhoto,jdbcType=VARCHAR},",
          "id_card_positive_photo = #{idCardPositivePhoto,jdbcType=VARCHAR},",
          "id_card_negative_photo = #{idCardNegativePhoto,jdbcType=VARCHAR},",
          "driving_licence_photo = #{drivingLicencePhoto,jdbcType=VARCHAR},",
          "car_running_photo = #{carRunningPhoto,jdbcType=VARCHAR},",
          "coach_certificate_photo = #{coachCertificatePhoto,jdbcType=VARCHAR},",
          "operation_certificate_photo = #{operationCertificatePhoto,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CoachCertificatePhoto record);
}