package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.CoachProduct;
import com.happydriving.rockets.server.entity.CoachProductExample;
import java.util.List;

import com.happydriving.rockets.server.model.CoachProductInfo;
import com.happydriving.rockets.server.model.CoachSelectCondition;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CoachProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_product
     *
     * @mbggenerated
     */
    int countByExample(CoachProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_product
     *
     * @mbggenerated
     */
    int deleteByExample(CoachProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_product
     *
     * @mbggenerated
     */
    @Delete({
        "delete from coach_product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_product
     *
     * @mbggenerated
     */
    @Insert({
        "insert into coach_product (id, user_id, ",
        "created_at, updated_at, ",
        "cartype_id, classtype_id, ",
        "price)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{cartypeId,jdbcType=INTEGER}, #{classtypeId,jdbcType=INTEGER}, ",
        "#{price,jdbcType=DECIMAL})"
    })
    int insert(CoachProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_product
     *
     * @mbggenerated
     */
    int insertSelective(CoachProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_product
     *
     * @mbggenerated
     */
    List<CoachProduct> selectByExample(CoachProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_product
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, user_id, created_at, updated_at, cartype_id, classtype_id, price",
        "from coach_product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    CoachProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoachProduct record, @Param("example") CoachProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoachProduct record, @Param("example") CoachProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoachProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach_product
     *
     * @mbggenerated
     */
    @Update({
        "update coach_product",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP},",
          "cartype_id = #{cartypeId,jdbcType=INTEGER},",
          "classtype_id = #{classtypeId,jdbcType=INTEGER},",
          "price = #{price,jdbcType=DECIMAL}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CoachProduct record);

    List<CoachProductInfo> getAllCoachProduceInfo(@Param("coachId") int coachId);


    void insertAndGetId(CoachProduct record);

    public List<CoachProductInfo> getCoachProductsByCondition(@Param("coachCondition")
                                                              CoachSelectCondition coachSelectCondition);

    public CoachProductInfo getCoachProductDetailById(@Param("productId") int productId);

}