package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.CourseType;
import com.happydriving.rockets.server.entity.CourseTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CourseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int countByExample(CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int deleteByExample(CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    @Delete({
        "delete from course_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
//    @Insert({
//        "insert into course_type (id, created_at, ",
//        "updated_at, course_name)",
//        "values (#{id,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP}, ",
//        "#{updatedAt,jdbcType=TIMESTAMP}, #{courseName,jdbcType=VARCHAR})"
//    })
    int selectCount(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int insertSelective(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    List<CourseType> selectByExample(CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, created_at, updated_at, course_name",
        "from course_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    CourseType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourseType record, @Param("example") CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourseType record, @Param("example") CourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_type
     *
     * @mbggenerated
     */
    @Update({
        "update course_type",
        "set created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP},",
          "course_name = #{courseName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CourseType record);
}