package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.DrivingSchoolDetail;
import com.happydriving.rockets.server.entity.DrivingSchoolDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface DrivingSchoolDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school_detail
     *
     * @mbggenerated
     */
    int countByExample(DrivingSchoolDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school_detail
     *
     * @mbggenerated
     */
    int deleteByExample(DrivingSchoolDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school_detail
     *
     * @mbggenerated
     */
    @Delete({
            "delete from driving_school_detail",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school_detail
     *
     * @mbggenerated
     */
    @Insert({
            "insert into driving_school_detail (id, school_id, ",
            "school_detail, school_imgurl, ",
            "school_avator)",
            "values (#{id,jdbcType=INTEGER}, #{schoolId,jdbcType=INTEGER}, ",
            "#{schoolDetail,jdbcType=VARCHAR}, #{schoolImgurl,jdbcType=VARCHAR}, ",
            "#{schoolAvator,jdbcType=VARCHAR})"
    })
    int insert(DrivingSchoolDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school_detail
     *
     * @mbggenerated
     */
    int insertSelective(DrivingSchoolDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school_detail
     *
     * @mbggenerated
     */
    List<DrivingSchoolDetail> selectByExample(DrivingSchoolDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school_detail
     *
     * @mbggenerated
     */
    @Select({
            "select",
            "id, school_id, school_detail, school_imgurl, school_avator",
            "from driving_school_detail",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    DrivingSchoolDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DrivingSchoolDetail record, @Param("example") DrivingSchoolDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DrivingSchoolDetail record, @Param("example") DrivingSchoolDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DrivingSchoolDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school_detail
     *
     * @mbggenerated
     */
    @Update({
            "update driving_school_detail",
            "set school_id = #{schoolId,jdbcType=INTEGER},",
            "school_detail = #{schoolDetail,jdbcType=VARCHAR},",
            "school_imgurl = #{schoolImgurl,jdbcType=VARCHAR},",
            "school_avator = #{schoolAvator,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DrivingSchoolDetail record);
}