package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.DsPotentialStudent;
import com.happydriving.rockets.server.entity.DsPotentialStudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface DsPotentialStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_potential_student
     *
     * @mbggenerated
     */
    int countByExample(DsPotentialStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_potential_student
     *
     * @mbggenerated
     */
    int deleteByExample(DsPotentialStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_potential_student
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ds_potential_student",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_potential_student
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ds_potential_student (ID, SERVICE_CITY_ID, ",
        "RECORD_DATE, INFO_CHANNEL, ",
        "NAME, PHONE, ADDRESS, ",
        "CONSULTANT_ID, REFERRER_ID, ",
        "PUSHER_ID, COMMENT, ",
        "NEXT_VISIT_DATE, IS_SIGNUP, ",
        "IS_INDIRECT, LAST_UPDATED_STAMP, ",
        "LAST_UPDATED_TX_STAMP, CREATED_STAMP, ",
        "CREATED_TX_STAMP, STUDENT_FOLLOW)",
        "values (#{id,jdbcType=VARCHAR}, #{serviceCityId,jdbcType=VARCHAR}, ",
        "#{recordDate,jdbcType=DATE}, #{infoChannel,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{consultantId,jdbcType=VARCHAR}, #{referrerId,jdbcType=VARCHAR}, ",
        "#{pusherId,jdbcType=VARCHAR}, #{comment,jdbcType=VARCHAR}, ",
        "#{nextVisitDate,jdbcType=DATE}, #{isSignup,jdbcType=CHAR}, ",
        "#{isIndirect,jdbcType=CHAR}, #{lastUpdatedStamp,jdbcType=TIMESTAMP}, ",
        "#{lastUpdatedTxStamp,jdbcType=TIMESTAMP}, #{createdStamp,jdbcType=TIMESTAMP}, ",
        "#{createdTxStamp,jdbcType=TIMESTAMP}, #{studentFollow,jdbcType=VARCHAR})"
    })
    int insert(DsPotentialStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_potential_student
     *
     * @mbggenerated
     */
    int insertSelective(DsPotentialStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_potential_student
     *
     * @mbggenerated
     */
    List<DsPotentialStudent> selectByExample(DsPotentialStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_potential_student
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, SERVICE_CITY_ID, RECORD_DATE, INFO_CHANNEL, NAME, PHONE, ADDRESS, CONSULTANT_ID, ",
        "REFERRER_ID, PUSHER_ID, COMMENT, NEXT_VISIT_DATE, IS_SIGNUP, IS_INDIRECT, LAST_UPDATED_STAMP, ",
        "LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP, STUDENT_FOLLOW",
        "from ds_potential_student",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    DsPotentialStudent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_potential_student
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DsPotentialStudent record, @Param("example") DsPotentialStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_potential_student
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DsPotentialStudent record, @Param("example") DsPotentialStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_potential_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DsPotentialStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds_potential_student
     *
     * @mbggenerated
     */
    @Update({
        "update ds_potential_student",
        "set SERVICE_CITY_ID = #{serviceCityId,jdbcType=VARCHAR},",
          "RECORD_DATE = #{recordDate,jdbcType=DATE},",
          "INFO_CHANNEL = #{infoChannel,jdbcType=VARCHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "PHONE = #{phone,jdbcType=VARCHAR},",
          "ADDRESS = #{address,jdbcType=VARCHAR},",
          "CONSULTANT_ID = #{consultantId,jdbcType=VARCHAR},",
          "REFERRER_ID = #{referrerId,jdbcType=VARCHAR},",
          "PUSHER_ID = #{pusherId,jdbcType=VARCHAR},",
          "COMMENT = #{comment,jdbcType=VARCHAR},",
          "NEXT_VISIT_DATE = #{nextVisitDate,jdbcType=DATE},",
          "IS_SIGNUP = #{isSignup,jdbcType=CHAR},",
          "IS_INDIRECT = #{isIndirect,jdbcType=CHAR},",
          "LAST_UPDATED_STAMP = #{lastUpdatedStamp,jdbcType=TIMESTAMP},",
          "LAST_UPDATED_TX_STAMP = #{lastUpdatedTxStamp,jdbcType=TIMESTAMP},",
          "CREATED_STAMP = #{createdStamp,jdbcType=TIMESTAMP},",
          "CREATED_TX_STAMP = #{createdTxStamp,jdbcType=TIMESTAMP},",
          "STUDENT_FOLLOW = #{studentFollow,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(DsPotentialStudent record);
}