package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.GuestTrack;
import com.happydriving.rockets.server.entity.GuestTrackExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GuestTrackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest_track
     *
     * @mbggenerated
     */
    int countByExample(GuestTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest_track
     *
     * @mbggenerated
     */
    int deleteByExample(GuestTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest_track
     *
     * @mbggenerated
     */
    @Delete({
        "delete from guest_track",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest_track
     *
     * @mbggenerated
     */
    @Insert({
        "insert into guest_track (id, phone, ",
        "user_type, created_at)",
        "values (#{id,jdbcType=INTEGER}, #{phone,jdbcType=VARCHAR}, ",
        "#{userType,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP})"
    })
    int insert(GuestTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest_track
     *
     * @mbggenerated
     */
    int insertSelective(GuestTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest_track
     *
     * @mbggenerated
     */
    List<GuestTrack> selectByExample(GuestTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest_track
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, phone, user_type, created_at",
        "from guest_track",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    GuestTrack selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest_track
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GuestTrack record, @Param("example") GuestTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest_track
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GuestTrack record, @Param("example") GuestTrackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest_track
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GuestTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guest_track
     *
     * @mbggenerated
     */
    @Update({
        "update guest_track",
        "set phone = #{phone,jdbcType=VARCHAR},",
          "user_type = #{userType,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(GuestTrack record);
}