package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.PotentialStudent;
import com.happydriving.rockets.server.entity.PotentialStudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PotentialStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table potential_student
     *
     * @mbggenerated
     */
    int countByExample(PotentialStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table potential_student
     *
     * @mbggenerated
     */
    int deleteByExample(PotentialStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table potential_student
     *
     * @mbggenerated
     */
    @Delete({
        "delete from potential_student",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table potential_student
     *
     * @mbggenerated
     */
    @Insert({
        "insert into potential_student (id, phone, ",
        "name, city, timestamp)",
        "values (#{id,jdbcType=INTEGER}, #{phone,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, #{timestamp,jdbcType=TIMESTAMP})"
    })
    int insert(PotentialStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table potential_student
     *
     * @mbggenerated
     */
    int insertSelective(PotentialStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table potential_student
     *
     * @mbggenerated
     */
    List<PotentialStudent> selectByExample(PotentialStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table potential_student
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, phone, name, city, timestamp",
        "from potential_student",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    PotentialStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table potential_student
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PotentialStudent record, @Param("example") PotentialStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table potential_student
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PotentialStudent record, @Param("example") PotentialStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table potential_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PotentialStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table potential_student
     *
     * @mbggenerated
     */
    @Update({
        "update potential_student",
        "set phone = #{phone,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "timestamp = #{timestamp,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PotentialStudent record);
}