package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.SchoolInfos;
import com.happydriving.rockets.server.entity.SchoolInfosExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface SchoolInfosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_infos
     *
     * @mbggenerated
     */
    int countByExample(SchoolInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_infos
     *
     * @mbggenerated
     */
    int deleteByExample(SchoolInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_infos
     *
     * @mbggenerated
     */
    @Delete({
        "delete from school_infos",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_infos
     *
     * @mbggenerated
     */
    @Insert({
        "insert into school_infos (id, training_area, ",
        "car_type, user_id, ",
        "created_at, updated_at, ",
        "t1, t2, t3, ",
        "t4)",
        "values (#{id,jdbcType=INTEGER}, #{trainingArea,jdbcType=VARCHAR}, ",
        "#{carType,jdbcType=VARCHAR}, #{userId,jdbcType=INTEGER}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{t1,jdbcType=VARCHAR}, #{t2,jdbcType=VARCHAR}, #{t3,jdbcType=VARCHAR}, ",
        "#{t4,jdbcType=VARCHAR})"
    })
    int insert(SchoolInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_infos
     *
     * @mbggenerated
     */
    int insertSelective(SchoolInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_infos
     *
     * @mbggenerated
     */
    List<SchoolInfos> selectByExample(SchoolInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_infos
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, training_area, car_type, user_id, created_at, updated_at, t1, t2, t3, t4",
        "from school_infos",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SchoolInfos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_infos
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SchoolInfos record, @Param("example") SchoolInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_infos
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SchoolInfos record, @Param("example") SchoolInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_infos
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SchoolInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_infos
     *
     * @mbggenerated
     */
    @Update({
        "update school_infos",
        "set training_area = #{trainingArea,jdbcType=VARCHAR},",
          "car_type = #{carType,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP},",
          "t1 = #{t1,jdbcType=VARCHAR},",
          "t2 = #{t2,jdbcType=VARCHAR},",
          "t3 = #{t3,jdbcType=VARCHAR},",
          "t4 = #{t4,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SchoolInfos record);
}