package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.ServiceStore;
import com.happydriving.rockets.server.entity.ServiceStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ServiceStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_store
     *
     * @mbggenerated
     */
    int countByExample(ServiceStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_store
     *
     * @mbggenerated
     */
    int deleteByExample(ServiceStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_store
     *
     * @mbggenerated
     */
    @Delete({
        "delete from service_store",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_store
     *
     * @mbggenerated
     */
    @Insert({
        "insert into service_store (id, service_city_id, ",
        "name, address, phone, ",
        "head)",
        "values (#{id,jdbcType=INTEGER}, #{serviceCityId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR}, ",
        "#{head,jdbcType=VARCHAR})"
    })
    int insert(ServiceStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_store
     *
     * @mbggenerated
     */
    int insertSelective(ServiceStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_store
     *
     * @mbggenerated
     */
    List<ServiceStore> selectByExample(ServiceStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_store
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, service_city_id, name, address, phone, head",
        "from service_store",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ServiceStore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_store
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ServiceStore record, @Param("example") ServiceStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_store
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ServiceStore record, @Param("example") ServiceStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_store
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ServiceStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_store
     *
     * @mbggenerated
     */
    @Update({
        "update service_store",
        "set service_city_id = #{serviceCityId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "head = #{head,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ServiceStore record);
}