package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.ServiceCity;
import com.happydriving.rockets.server.entity.ServiceCityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ServiceCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_city
     *
     * @mbggenerated
     */
    int countByExample(ServiceCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_city
     *
     * @mbggenerated
     */
    int deleteByExample(ServiceCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_city
     *
     * @mbggenerated
     */
    @Delete({
        "delete from service_city",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_city
     *
     * @mbggenerated
     */
    @Insert({
        "insert into service_city (id, name, ",
        "latitude, longitude)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{latitude,jdbcType=DECIMAL}, #{longitude,jdbcType=DECIMAL})"
    })
    int insert(ServiceCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_city
     *
     * @mbggenerated
     */
    int insertSelective(ServiceCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_city
     *
     * @mbggenerated
     */
    List<ServiceCity> selectByExample(ServiceCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_city
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, latitude, longitude",
        "from service_city",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ServiceCity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_city
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ServiceCity record, @Param("example") ServiceCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_city
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ServiceCity record, @Param("example") ServiceCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ServiceCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_city
     *
     * @mbggenerated
     */
    @Update({
        "update service_city",
        "set name = #{name,jdbcType=VARCHAR},",
          "latitude = #{latitude,jdbcType=DECIMAL},",
          "longitude = #{longitude,jdbcType=DECIMAL}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ServiceCity record);
}