package com.happydriving.rockets.server.mapper;

import com.happydriving.rockets.server.entity.StudentSchedule;
import com.happydriving.rockets.server.entity.StudentScheduleExample;
import java.util.List;

import com.happydriving.rockets.server.model.StudentScheduleDetailInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface StudentScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_schedule
     *
     * @mbggenerated
     */
    int countByExample(StudentScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_schedule
     *
     * @mbggenerated
     */
    int deleteByExample(StudentScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_schedule
     *
     * @mbggenerated
     */
    @Delete({
        "delete from student_schedule",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_schedule
     *
     * @mbggenerated
     */
    @Insert({
        "insert into student_schedule (id, user_id, ",
        "coach_schedule_id, created_at, ",
        "updated_at)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{coachScheduleId,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(StudentSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_schedule
     *
     * @mbggenerated
     */
    int insertSelective(StudentSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_schedule
     *
     * @mbggenerated
     */
    List<StudentSchedule> selectByExample(StudentScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_schedule
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, user_id, coach_schedule_id, created_at, updated_at",
        "from student_schedule",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    StudentSchedule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_schedule
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StudentSchedule record, @Param("example") StudentScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_schedule
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StudentSchedule record, @Param("example") StudentScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_schedule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudentSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_schedule
     *
     * @mbggenerated
     */
    @Update({
        "update student_schedule",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "coach_schedule_id = #{coachScheduleId,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(StudentSchedule record);

    List<StudentScheduleDetailInfo> getStudentScheduleDetailById(@Param("studentId") int studentId);

    void insertAndGetId(StudentSchedule studentSchedule);

}