package com.happydriving.rockets.server.entity;

import java.util.Date;

public class CoachAuditInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_auditinfo.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_auditinfo.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_auditinfo.audit_admin
     *
     * @mbggenerated
     */
    private String auditAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_auditinfo.audit_status
     *
     * @mbggenerated
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_auditinfo.audit_message
     *
     * @mbggenerated
     */
    private String auditMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_auditinfo.audit_at
     *
     * @mbggenerated
     */
    private Date auditAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_auditinfo.mark
     *
     * @mbggenerated
     */
    private Boolean mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_auditinfo.label
     *
     * @mbggenerated
     */
    private String label;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_auditinfo.ID
     *
     * @return the value of coach_auditinfo.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_auditinfo.ID
     *
     * @param id the value for coach_auditinfo.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_auditinfo.user_id
     *
     * @return the value of coach_auditinfo.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_auditinfo.user_id
     *
     * @param userId the value for coach_auditinfo.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_auditinfo.audit_admin
     *
     * @return the value of coach_auditinfo.audit_admin
     *
     * @mbggenerated
     */
    public String getAuditAdmin() {
        return auditAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_auditinfo.audit_admin
     *
     * @param auditAdmin the value for coach_auditinfo.audit_admin
     *
     * @mbggenerated
     */
    public void setAuditAdmin(String auditAdmin) {
        this.auditAdmin = auditAdmin == null ? null : auditAdmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_auditinfo.audit_status
     *
     * @return the value of coach_auditinfo.audit_status
     *
     * @mbggenerated
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_auditinfo.audit_status
     *
     * @param auditStatus the value for coach_auditinfo.audit_status
     *
     * @mbggenerated
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_auditinfo.audit_message
     *
     * @return the value of coach_auditinfo.audit_message
     *
     * @mbggenerated
     */
    public String getAuditMessage() {
        return auditMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_auditinfo.audit_message
     *
     * @param auditMessage the value for coach_auditinfo.audit_message
     *
     * @mbggenerated
     */
    public void setAuditMessage(String auditMessage) {
        this.auditMessage = auditMessage == null ? null : auditMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_auditinfo.audit_at
     *
     * @return the value of coach_auditinfo.audit_at
     *
     * @mbggenerated
     */
    public Date getAuditAt() {
        return auditAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_auditinfo.audit_at
     *
     * @param auditAt the value for coach_auditinfo.audit_at
     *
     * @mbggenerated
     */
    public void setAuditAt(Date auditAt) {
        this.auditAt = auditAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_auditinfo.mark
     *
     * @return the value of coach_auditinfo.mark
     *
     * @mbggenerated
     */
    public Boolean getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_auditinfo.mark
     *
     * @param mark the value for coach_auditinfo.mark
     *
     * @mbggenerated
     */
    public void setMark(Boolean mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_auditinfo.label
     *
     * @return the value of coach_auditinfo.label
     *
     * @mbggenerated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_auditinfo.label
     *
     * @param label the value for coach_auditinfo.label
     *
     * @mbggenerated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }
}