package com.happydriving.rockets.server.entity;

import java.util.Date;

public class CoachUploadPhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_upload_photo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_upload_photo.coach_id
     *
     * @mbggenerated
     */
    private Integer coachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_upload_photo.upload_photo
     *
     * @mbggenerated
     */
    private String uploadPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_upload_photo.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_upload_photo.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_upload_photo.id
     *
     * @return the value of coach_upload_photo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_upload_photo.id
     *
     * @param id the value for coach_upload_photo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_upload_photo.coach_id
     *
     * @return the value of coach_upload_photo.coach_id
     *
     * @mbggenerated
     */
    public Integer getCoachId() {
        return coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_upload_photo.coach_id
     *
     * @param coachId the value for coach_upload_photo.coach_id
     *
     * @mbggenerated
     */
    public void setCoachId(Integer coachId) {
        this.coachId = coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_upload_photo.upload_photo
     *
     * @return the value of coach_upload_photo.upload_photo
     *
     * @mbggenerated
     */
    public String getUploadPhoto() {
        return uploadPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_upload_photo.upload_photo
     *
     * @param uploadPhoto the value for coach_upload_photo.upload_photo
     *
     * @mbggenerated
     */
    public void setUploadPhoto(String uploadPhoto) {
        this.uploadPhoto = uploadPhoto == null ? null : uploadPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_upload_photo.created_at
     *
     * @return the value of coach_upload_photo.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_upload_photo.created_at
     *
     * @param createdAt the value for coach_upload_photo.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_upload_photo.updated_at
     *
     * @return the value of coach_upload_photo.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_upload_photo.updated_at
     *
     * @param updatedAt the value for coach_upload_photo.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}