package com.happydriving.rockets.server.entity;

import java.util.Date;

public class CoachSchedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.starttime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.endtime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.province_id
     *
     * @mbggenerated
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.county_id
     *
     * @mbggenerated
     */
    private Integer countyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.town_id
     *
     * @mbggenerated
     */
    private Integer townId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.addr_in_detail
     *
     * @mbggenerated
     */
    private String addrInDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.cartype_id
     *
     * @mbggenerated
     */
    private Integer cartypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.coursetype_id
     *
     * @mbggenerated
     */
    private Integer coursetypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_schedule.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.id
     *
     * @return the value of coach_schedule.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.id
     *
     * @param id the value for coach_schedule.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.starttime
     *
     * @return the value of coach_schedule.starttime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.starttime
     *
     * @param starttime the value for coach_schedule.starttime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.endtime
     *
     * @return the value of coach_schedule.endtime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.endtime
     *
     * @param endtime the value for coach_schedule.endtime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.user_id
     *
     * @return the value of coach_schedule.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.user_id
     *
     * @param userId the value for coach_schedule.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.province_id
     *
     * @return the value of coach_schedule.province_id
     *
     * @mbggenerated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.province_id
     *
     * @param provinceId the value for coach_schedule.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.city_id
     *
     * @return the value of coach_schedule.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.city_id
     *
     * @param cityId the value for coach_schedule.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.county_id
     *
     * @return the value of coach_schedule.county_id
     *
     * @mbggenerated
     */
    public Integer getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.county_id
     *
     * @param countyId the value for coach_schedule.county_id
     *
     * @mbggenerated
     */
    public void setCountyId(Integer countyId) {
        this.countyId = countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.town_id
     *
     * @return the value of coach_schedule.town_id
     *
     * @mbggenerated
     */
    public Integer getTownId() {
        return townId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.town_id
     *
     * @param townId the value for coach_schedule.town_id
     *
     * @mbggenerated
     */
    public void setTownId(Integer townId) {
        this.townId = townId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.addr_in_detail
     *
     * @return the value of coach_schedule.addr_in_detail
     *
     * @mbggenerated
     */
    public String getAddrInDetail() {
        return addrInDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.addr_in_detail
     *
     * @param addrInDetail the value for coach_schedule.addr_in_detail
     *
     * @mbggenerated
     */
    public void setAddrInDetail(String addrInDetail) {
        this.addrInDetail = addrInDetail == null ? null : addrInDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.cartype_id
     *
     * @return the value of coach_schedule.cartype_id
     *
     * @mbggenerated
     */
    public Integer getCartypeId() {
        return cartypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.cartype_id
     *
     * @param cartypeId the value for coach_schedule.cartype_id
     *
     * @mbggenerated
     */
    public void setCartypeId(Integer cartypeId) {
        this.cartypeId = cartypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.coursetype_id
     *
     * @return the value of coach_schedule.coursetype_id
     *
     * @mbggenerated
     */
    public Integer getCoursetypeId() {
        return coursetypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.coursetype_id
     *
     * @param coursetypeId the value for coach_schedule.coursetype_id
     *
     * @mbggenerated
     */
    public void setCoursetypeId(Integer coursetypeId) {
        this.coursetypeId = coursetypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.created_at
     *
     * @return the value of coach_schedule.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.created_at
     *
     * @param createdAt the value for coach_schedule.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_schedule.updated_at
     *
     * @return the value of coach_schedule.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_schedule.updated_at
     *
     * @param updatedAt the value for coach_schedule.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        return "CoachSchedule{" +
                "id=" + id +
                ", starttime=" + starttime +
                ", endtime=" + endtime +
                ", userId=" + userId +
                ", provinceId=" + provinceId +
                ", cityId=" + cityId +
                ", countyId=" + countyId +
                ", townId=" + townId +
                ", addrInDetail='" + addrInDetail + '\'' +
                ", cartypeId=" + cartypeId +
                ", coursetypeId=" + coursetypeId +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
}