package com.happydriving.rockets.server.entity;

public class County {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.Code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.CityID
     *
     * @mbggenerated
     */
    private Integer cityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.ID
     *
     * @return the value of county.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.ID
     *
     * @param id the value for county.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.Name
     *
     * @return the value of county.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.Name
     *
     * @param name the value for county.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.Code
     *
     * @return the value of county.Code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.Code
     *
     * @param code the value for county.Code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.CityID
     *
     * @return the value of county.CityID
     *
     * @mbggenerated
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.CityID
     *
     * @param cityid the value for county.CityID
     *
     * @mbggenerated
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }
}