package com.happydriving.rockets.server.entity;

public class DrivingSchoolDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driving_school_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driving_school_detail.school_id
     *
     * @mbggenerated
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driving_school_detail.school_detail
     *
     * @mbggenerated
     */
    private String schoolDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driving_school_detail.school_imgurl
     *
     * @mbggenerated
     */
    private String schoolImgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driving_school_detail.school_avator
     *
     * @mbggenerated
     */
    private String schoolAvator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driving_school_detail.id
     *
     * @return the value of driving_school_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driving_school_detail.id
     *
     * @param id the value for driving_school_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driving_school_detail.school_id
     *
     * @return the value of driving_school_detail.school_id
     *
     * @mbggenerated
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driving_school_detail.school_id
     *
     * @param schoolId the value for driving_school_detail.school_id
     *
     * @mbggenerated
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driving_school_detail.school_detail
     *
     * @return the value of driving_school_detail.school_detail
     *
     * @mbggenerated
     */
    public String getSchoolDetail() {
        return schoolDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driving_school_detail.school_detail
     *
     * @param schoolDetail the value for driving_school_detail.school_detail
     *
     * @mbggenerated
     */
    public void setSchoolDetail(String schoolDetail) {
        this.schoolDetail = schoolDetail == null ? null : schoolDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driving_school_detail.school_imgurl
     *
     * @return the value of driving_school_detail.school_imgurl
     *
     * @mbggenerated
     */
    public String getSchoolImgurl() {
        return schoolImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driving_school_detail.school_imgurl
     *
     * @param schoolImgurl the value for driving_school_detail.school_imgurl
     *
     * @mbggenerated
     */
    public void setSchoolImgurl(String schoolImgurl) {
        this.schoolImgurl = schoolImgurl == null ? null : schoolImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driving_school_detail.school_avator
     *
     * @return the value of driving_school_detail.school_avator
     *
     * @mbggenerated
     */
    public String getSchoolAvator() {
        return schoolAvator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driving_school_detail.school_avator
     *
     * @param schoolAvator the value for driving_school_detail.school_avator
     *
     * @mbggenerated
     */
    public void setSchoolAvator(String schoolAvator) {
        this.schoolAvator = schoolAvator == null ? null : schoolAvator.trim();
    }
}