package com.happydriving.rockets.server.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DrivingSchoolExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    public DrivingSchoolExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andServiceCityIdIsNull() {
            addCriterion("service_city_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceCityIdIsNotNull() {
            addCriterion("service_city_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceCityIdEqualTo(Integer value) {
            addCriterion("service_city_id =", value, "serviceCityId");
            return (Criteria) this;
        }

        public Criteria andServiceCityIdNotEqualTo(Integer value) {
            addCriterion("service_city_id <>", value, "serviceCityId");
            return (Criteria) this;
        }

        public Criteria andServiceCityIdGreaterThan(Integer value) {
            addCriterion("service_city_id >", value, "serviceCityId");
            return (Criteria) this;
        }

        public Criteria andServiceCityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("service_city_id >=", value, "serviceCityId");
            return (Criteria) this;
        }

        public Criteria andServiceCityIdLessThan(Integer value) {
            addCriterion("service_city_id <", value, "serviceCityId");
            return (Criteria) this;
        }

        public Criteria andServiceCityIdLessThanOrEqualTo(Integer value) {
            addCriterion("service_city_id <=", value, "serviceCityId");
            return (Criteria) this;
        }

        public Criteria andServiceCityIdIn(List<Integer> values) {
            addCriterion("service_city_id in", values, "serviceCityId");
            return (Criteria) this;
        }

        public Criteria andServiceCityIdNotIn(List<Integer> values) {
            addCriterion("service_city_id not in", values, "serviceCityId");
            return (Criteria) this;
        }

        public Criteria andServiceCityIdBetween(Integer value1, Integer value2) {
            addCriterion("service_city_id between", value1, value2, "serviceCityId");
            return (Criteria) this;
        }

        public Criteria andServiceCityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("service_city_id not between", value1, value2, "serviceCityId");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIsNull() {
            addCriterion("school_name is null");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIsNotNull() {
            addCriterion("school_name is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolNameEqualTo(String value) {
            addCriterion("school_name =", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotEqualTo(String value) {
            addCriterion("school_name <>", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameGreaterThan(String value) {
            addCriterion("school_name >", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameGreaterThanOrEqualTo(String value) {
            addCriterion("school_name >=", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLessThan(String value) {
            addCriterion("school_name <", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLessThanOrEqualTo(String value) {
            addCriterion("school_name <=", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLike(String value) {
            addCriterion("school_name like", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotLike(String value) {
            addCriterion("school_name not like", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIn(List<String> values) {
            addCriterion("school_name in", values, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotIn(List<String> values) {
            addCriterion("school_name not in", values, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameBetween(String value1, String value2) {
            addCriterion("school_name between", value1, value2, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotBetween(String value1, String value2) {
            addCriterion("school_name not between", value1, value2, "schoolName");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("level like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("level not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(BigDecimal value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(BigDecimal value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(BigDecimal value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(BigDecimal value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<BigDecimal> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<BigDecimal> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(BigDecimal value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(BigDecimal value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(BigDecimal value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(BigDecimal value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<BigDecimal> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<BigDecimal> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTxStampIsNull() {
            addCriterion("LAST_UPDATED_TX_STAMP is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTxStampIsNotNull() {
            addCriterion("LAST_UPDATED_TX_STAMP is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTxStampEqualTo(Date value) {
            addCriterion("LAST_UPDATED_TX_STAMP =", value, "lastUpdatedTxStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTxStampNotEqualTo(Date value) {
            addCriterion("LAST_UPDATED_TX_STAMP <>", value, "lastUpdatedTxStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTxStampGreaterThan(Date value) {
            addCriterion("LAST_UPDATED_TX_STAMP >", value, "lastUpdatedTxStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTxStampGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATED_TX_STAMP >=", value, "lastUpdatedTxStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTxStampLessThan(Date value) {
            addCriterion("LAST_UPDATED_TX_STAMP <", value, "lastUpdatedTxStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTxStampLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATED_TX_STAMP <=", value, "lastUpdatedTxStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTxStampIn(List<Date> values) {
            addCriterion("LAST_UPDATED_TX_STAMP in", values, "lastUpdatedTxStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTxStampNotIn(List<Date> values) {
            addCriterion("LAST_UPDATED_TX_STAMP not in", values, "lastUpdatedTxStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTxStampBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATED_TX_STAMP between", value1, value2, "lastUpdatedTxStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedTxStampNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATED_TX_STAMP not between", value1, value2, "lastUpdatedTxStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedStampIsNull() {
            addCriterion("LAST_UPDATED_STAMP is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedStampIsNotNull() {
            addCriterion("LAST_UPDATED_STAMP is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedStampEqualTo(Date value) {
            addCriterion("LAST_UPDATED_STAMP =", value, "lastUpdatedStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedStampNotEqualTo(Date value) {
            addCriterion("LAST_UPDATED_STAMP <>", value, "lastUpdatedStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedStampGreaterThan(Date value) {
            addCriterion("LAST_UPDATED_STAMP >", value, "lastUpdatedStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATED_STAMP >=", value, "lastUpdatedStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedStampLessThan(Date value) {
            addCriterion("LAST_UPDATED_STAMP <", value, "lastUpdatedStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedStampLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATED_STAMP <=", value, "lastUpdatedStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedStampIn(List<Date> values) {
            addCriterion("LAST_UPDATED_STAMP in", values, "lastUpdatedStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedStampNotIn(List<Date> values) {
            addCriterion("LAST_UPDATED_STAMP not in", values, "lastUpdatedStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedStampBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATED_STAMP between", value1, value2, "lastUpdatedStamp");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedStampNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATED_STAMP not between", value1, value2, "lastUpdatedStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNull() {
            addCriterion("CREATED_STAMP is null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNotNull() {
            addCriterion("CREATED_STAMP is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampEqualTo(Date value) {
            addCriterion("CREATED_STAMP =", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotEqualTo(Date value) {
            addCriterion("CREATED_STAMP <>", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThan(Date value) {
            addCriterion("CREATED_STAMP >", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_STAMP >=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThan(Date value) {
            addCriterion("CREATED_STAMP <", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_STAMP <=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIn(List<Date> values) {
            addCriterion("CREATED_STAMP in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotIn(List<Date> values) {
            addCriterion("CREATED_STAMP not in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampBetween(Date value1, Date value2) {
            addCriterion("CREATED_STAMP between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_STAMP not between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andLongtitudeIsNull() {
            addCriterion("LONGTITUDE is null");
            return (Criteria) this;
        }

        public Criteria andLongtitudeIsNotNull() {
            addCriterion("LONGTITUDE is not null");
            return (Criteria) this;
        }

        public Criteria andLongtitudeEqualTo(BigDecimal value) {
            addCriterion("LONGTITUDE =", value, "longtitude");
            return (Criteria) this;
        }

        public Criteria andLongtitudeNotEqualTo(BigDecimal value) {
            addCriterion("LONGTITUDE <>", value, "longtitude");
            return (Criteria) this;
        }

        public Criteria andLongtitudeGreaterThan(BigDecimal value) {
            addCriterion("LONGTITUDE >", value, "longtitude");
            return (Criteria) this;
        }

        public Criteria andLongtitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LONGTITUDE >=", value, "longtitude");
            return (Criteria) this;
        }

        public Criteria andLongtitudeLessThan(BigDecimal value) {
            addCriterion("LONGTITUDE <", value, "longtitude");
            return (Criteria) this;
        }

        public Criteria andLongtitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LONGTITUDE <=", value, "longtitude");
            return (Criteria) this;
        }

        public Criteria andLongtitudeIn(List<BigDecimal> values) {
            addCriterion("LONGTITUDE in", values, "longtitude");
            return (Criteria) this;
        }

        public Criteria andLongtitudeNotIn(List<BigDecimal> values) {
            addCriterion("LONGTITUDE not in", values, "longtitude");
            return (Criteria) this;
        }

        public Criteria andLongtitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LONGTITUDE between", value1, value2, "longtitude");
            return (Criteria) this;
        }

        public Criteria andLongtitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LONGTITUDE not between", value1, value2, "longtitude");
            return (Criteria) this;
        }

        public Criteria andCreatedTxStampIsNull() {
            addCriterion("CREATED_TX_STAMP is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTxStampIsNotNull() {
            addCriterion("CREATED_TX_STAMP is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTxStampEqualTo(Date value) {
            addCriterion("CREATED_TX_STAMP =", value, "createdTxStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedTxStampNotEqualTo(Date value) {
            addCriterion("CREATED_TX_STAMP <>", value, "createdTxStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedTxStampGreaterThan(Date value) {
            addCriterion("CREATED_TX_STAMP >", value, "createdTxStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedTxStampGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_TX_STAMP >=", value, "createdTxStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedTxStampLessThan(Date value) {
            addCriterion("CREATED_TX_STAMP <", value, "createdTxStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedTxStampLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_TX_STAMP <=", value, "createdTxStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedTxStampIn(List<Date> values) {
            addCriterion("CREATED_TX_STAMP in", values, "createdTxStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedTxStampNotIn(List<Date> values) {
            addCriterion("CREATED_TX_STAMP not in", values, "createdTxStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedTxStampBetween(Date value1, Date value2) {
            addCriterion("CREATED_TX_STAMP between", value1, value2, "createdTxStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedTxStampNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_TX_STAMP not between", value1, value2, "createdTxStamp");
            return (Criteria) this;
        }

        public Criteria andIsHideIsNull() {
            addCriterion("is_hide is null");
            return (Criteria) this;
        }

        public Criteria andIsHideIsNotNull() {
            addCriterion("is_hide is not null");
            return (Criteria) this;
        }

        public Criteria andIsHideEqualTo(String value) {
            addCriterion("is_hide =", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideNotEqualTo(String value) {
            addCriterion("is_hide <>", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideGreaterThan(String value) {
            addCriterion("is_hide >", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideGreaterThanOrEqualTo(String value) {
            addCriterion("is_hide >=", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideLessThan(String value) {
            addCriterion("is_hide <", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideLessThanOrEqualTo(String value) {
            addCriterion("is_hide <=", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideLike(String value) {
            addCriterion("is_hide like", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideNotLike(String value) {
            addCriterion("is_hide not like", value, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideIn(List<String> values) {
            addCriterion("is_hide in", values, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideNotIn(List<String> values) {
            addCriterion("is_hide not in", values, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideBetween(String value1, String value2) {
            addCriterion("is_hide between", value1, value2, "isHide");
            return (Criteria) this;
        }

        public Criteria andIsHideNotBetween(String value1, String value2) {
            addCriterion("is_hide not between", value1, value2, "isHide");
            return (Criteria) this;
        }

        public Criteria andCanSelectIsNull() {
            addCriterion("can_select is null");
            return (Criteria) this;
        }

        public Criteria andCanSelectIsNotNull() {
            addCriterion("can_select is not null");
            return (Criteria) this;
        }

        public Criteria andCanSelectEqualTo(String value) {
            addCriterion("can_select =", value, "canSelect");
            return (Criteria) this;
        }

        public Criteria andCanSelectNotEqualTo(String value) {
            addCriterion("can_select <>", value, "canSelect");
            return (Criteria) this;
        }

        public Criteria andCanSelectGreaterThan(String value) {
            addCriterion("can_select >", value, "canSelect");
            return (Criteria) this;
        }

        public Criteria andCanSelectGreaterThanOrEqualTo(String value) {
            addCriterion("can_select >=", value, "canSelect");
            return (Criteria) this;
        }

        public Criteria andCanSelectLessThan(String value) {
            addCriterion("can_select <", value, "canSelect");
            return (Criteria) this;
        }

        public Criteria andCanSelectLessThanOrEqualTo(String value) {
            addCriterion("can_select <=", value, "canSelect");
            return (Criteria) this;
        }

        public Criteria andCanSelectLike(String value) {
            addCriterion("can_select like", value, "canSelect");
            return (Criteria) this;
        }

        public Criteria andCanSelectNotLike(String value) {
            addCriterion("can_select not like", value, "canSelect");
            return (Criteria) this;
        }

        public Criteria andCanSelectIn(List<String> values) {
            addCriterion("can_select in", values, "canSelect");
            return (Criteria) this;
        }

        public Criteria andCanSelectNotIn(List<String> values) {
            addCriterion("can_select not in", values, "canSelect");
            return (Criteria) this;
        }

        public Criteria andCanSelectBetween(String value1, String value2) {
            addCriterion("can_select between", value1, value2, "canSelect");
            return (Criteria) this;
        }

        public Criteria andCanSelectNotBetween(String value1, String value2) {
            addCriterion("can_select not between", value1, value2, "canSelect");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailIsNull() {
            addCriterion("school_detail is null");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailIsNotNull() {
            addCriterion("school_detail is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailEqualTo(String value) {
            addCriterion("school_detail =", value, "schoolDetail");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailNotEqualTo(String value) {
            addCriterion("school_detail <>", value, "schoolDetail");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailGreaterThan(String value) {
            addCriterion("school_detail >", value, "schoolDetail");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailGreaterThanOrEqualTo(String value) {
            addCriterion("school_detail >=", value, "schoolDetail");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailLessThan(String value) {
            addCriterion("school_detail <", value, "schoolDetail");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailLessThanOrEqualTo(String value) {
            addCriterion("school_detail <=", value, "schoolDetail");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailLike(String value) {
            addCriterion("school_detail like", value, "schoolDetail");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailNotLike(String value) {
            addCriterion("school_detail not like", value, "schoolDetail");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailIn(List<String> values) {
            addCriterion("school_detail in", values, "schoolDetail");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailNotIn(List<String> values) {
            addCriterion("school_detail not in", values, "schoolDetail");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailBetween(String value1, String value2) {
            addCriterion("school_detail between", value1, value2, "schoolDetail");
            return (Criteria) this;
        }

        public Criteria andSchoolDetailNotBetween(String value1, String value2) {
            addCriterion("school_detail not between", value1, value2, "schoolDetail");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlIsNull() {
            addCriterion("school_imgurl is null");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlIsNotNull() {
            addCriterion("school_imgurl is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlEqualTo(String value) {
            addCriterion("school_imgurl =", value, "schoolImgurl");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlNotEqualTo(String value) {
            addCriterion("school_imgurl <>", value, "schoolImgurl");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlGreaterThan(String value) {
            addCriterion("school_imgurl >", value, "schoolImgurl");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlGreaterThanOrEqualTo(String value) {
            addCriterion("school_imgurl >=", value, "schoolImgurl");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlLessThan(String value) {
            addCriterion("school_imgurl <", value, "schoolImgurl");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlLessThanOrEqualTo(String value) {
            addCriterion("school_imgurl <=", value, "schoolImgurl");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlLike(String value) {
            addCriterion("school_imgurl like", value, "schoolImgurl");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlNotLike(String value) {
            addCriterion("school_imgurl not like", value, "schoolImgurl");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlIn(List<String> values) {
            addCriterion("school_imgurl in", values, "schoolImgurl");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlNotIn(List<String> values) {
            addCriterion("school_imgurl not in", values, "schoolImgurl");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlBetween(String value1, String value2) {
            addCriterion("school_imgurl between", value1, value2, "schoolImgurl");
            return (Criteria) this;
        }

        public Criteria andSchoolImgurlNotBetween(String value1, String value2) {
            addCriterion("school_imgurl not between", value1, value2, "schoolImgurl");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorIsNull() {
            addCriterion("school_avator is null");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorIsNotNull() {
            addCriterion("school_avator is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorEqualTo(String value) {
            addCriterion("school_avator =", value, "schoolAvator");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorNotEqualTo(String value) {
            addCriterion("school_avator <>", value, "schoolAvator");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorGreaterThan(String value) {
            addCriterion("school_avator >", value, "schoolAvator");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorGreaterThanOrEqualTo(String value) {
            addCriterion("school_avator >=", value, "schoolAvator");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorLessThan(String value) {
            addCriterion("school_avator <", value, "schoolAvator");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorLessThanOrEqualTo(String value) {
            addCriterion("school_avator <=", value, "schoolAvator");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorLike(String value) {
            addCriterion("school_avator like", value, "schoolAvator");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorNotLike(String value) {
            addCriterion("school_avator not like", value, "schoolAvator");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorIn(List<String> values) {
            addCriterion("school_avator in", values, "schoolAvator");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorNotIn(List<String> values) {
            addCriterion("school_avator not in", values, "schoolAvator");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorBetween(String value1, String value2) {
            addCriterion("school_avator between", value1, value2, "schoolAvator");
            return (Criteria) this;
        }

        public Criteria andSchoolAvatorNotBetween(String value1, String value2) {
            addCriterion("school_avator not between", value1, value2, "schoolAvator");
            return (Criteria) this;
        }

        public Criteria andSchoolHdIsNull() {
            addCriterion("school_hd is null");
            return (Criteria) this;
        }

        public Criteria andSchoolHdIsNotNull() {
            addCriterion("school_hd is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolHdEqualTo(String value) {
            addCriterion("school_hd =", value, "schoolHd");
            return (Criteria) this;
        }

        public Criteria andSchoolHdNotEqualTo(String value) {
            addCriterion("school_hd <>", value, "schoolHd");
            return (Criteria) this;
        }

        public Criteria andSchoolHdGreaterThan(String value) {
            addCriterion("school_hd >", value, "schoolHd");
            return (Criteria) this;
        }

        public Criteria andSchoolHdGreaterThanOrEqualTo(String value) {
            addCriterion("school_hd >=", value, "schoolHd");
            return (Criteria) this;
        }

        public Criteria andSchoolHdLessThan(String value) {
            addCriterion("school_hd <", value, "schoolHd");
            return (Criteria) this;
        }

        public Criteria andSchoolHdLessThanOrEqualTo(String value) {
            addCriterion("school_hd <=", value, "schoolHd");
            return (Criteria) this;
        }

        public Criteria andSchoolHdLike(String value) {
            addCriterion("school_hd like", value, "schoolHd");
            return (Criteria) this;
        }

        public Criteria andSchoolHdNotLike(String value) {
            addCriterion("school_hd not like", value, "schoolHd");
            return (Criteria) this;
        }

        public Criteria andSchoolHdIn(List<String> values) {
            addCriterion("school_hd in", values, "schoolHd");
            return (Criteria) this;
        }

        public Criteria andSchoolHdNotIn(List<String> values) {
            addCriterion("school_hd not in", values, "schoolHd");
            return (Criteria) this;
        }

        public Criteria andSchoolHdBetween(String value1, String value2) {
            addCriterion("school_hd between", value1, value2, "schoolHd");
            return (Criteria) this;
        }

        public Criteria andSchoolHdNotBetween(String value1, String value2) {
            addCriterion("school_hd not between", value1, value2, "schoolHd");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexIsNull() {
            addCriterion("school_index is null");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexIsNotNull() {
            addCriterion("school_index is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexEqualTo(String value) {
            addCriterion("school_index =", value, "schoolIndex");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexNotEqualTo(String value) {
            addCriterion("school_index <>", value, "schoolIndex");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexGreaterThan(String value) {
            addCriterion("school_index >", value, "schoolIndex");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexGreaterThanOrEqualTo(String value) {
            addCriterion("school_index >=", value, "schoolIndex");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexLessThan(String value) {
            addCriterion("school_index <", value, "schoolIndex");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexLessThanOrEqualTo(String value) {
            addCriterion("school_index <=", value, "schoolIndex");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexLike(String value) {
            addCriterion("school_index like", value, "schoolIndex");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexNotLike(String value) {
            addCriterion("school_index not like", value, "schoolIndex");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexIn(List<String> values) {
            addCriterion("school_index in", values, "schoolIndex");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexNotIn(List<String> values) {
            addCriterion("school_index not in", values, "schoolIndex");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexBetween(String value1, String value2) {
            addCriterion("school_index between", value1, value2, "schoolIndex");
            return (Criteria) this;
        }

        public Criteria andSchoolIndexNotBetween(String value1, String value2) {
            addCriterion("school_index not between", value1, value2, "schoolIndex");
            return (Criteria) this;
        }

        public Criteria andShortAddressIsNull() {
            addCriterion("short_address is null");
            return (Criteria) this;
        }

        public Criteria andShortAddressIsNotNull() {
            addCriterion("short_address is not null");
            return (Criteria) this;
        }

        public Criteria andShortAddressEqualTo(String value) {
            addCriterion("short_address =", value, "shortAddress");
            return (Criteria) this;
        }

        public Criteria andShortAddressNotEqualTo(String value) {
            addCriterion("short_address <>", value, "shortAddress");
            return (Criteria) this;
        }

        public Criteria andShortAddressGreaterThan(String value) {
            addCriterion("short_address >", value, "shortAddress");
            return (Criteria) this;
        }

        public Criteria andShortAddressGreaterThanOrEqualTo(String value) {
            addCriterion("short_address >=", value, "shortAddress");
            return (Criteria) this;
        }

        public Criteria andShortAddressLessThan(String value) {
            addCriterion("short_address <", value, "shortAddress");
            return (Criteria) this;
        }

        public Criteria andShortAddressLessThanOrEqualTo(String value) {
            addCriterion("short_address <=", value, "shortAddress");
            return (Criteria) this;
        }

        public Criteria andShortAddressLike(String value) {
            addCriterion("short_address like", value, "shortAddress");
            return (Criteria) this;
        }

        public Criteria andShortAddressNotLike(String value) {
            addCriterion("short_address not like", value, "shortAddress");
            return (Criteria) this;
        }

        public Criteria andShortAddressIn(List<String> values) {
            addCriterion("short_address in", values, "shortAddress");
            return (Criteria) this;
        }

        public Criteria andShortAddressNotIn(List<String> values) {
            addCriterion("short_address not in", values, "shortAddress");
            return (Criteria) this;
        }

        public Criteria andShortAddressBetween(String value1, String value2) {
            addCriterion("short_address between", value1, value2, "shortAddress");
            return (Criteria) this;
        }

        public Criteria andShortAddressNotBetween(String value1, String value2) {
            addCriterion("short_address not between", value1, value2, "shortAddress");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberIsNull() {
            addCriterion("register_number is null");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberIsNotNull() {
            addCriterion("register_number is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberEqualTo(Integer value) {
            addCriterion("register_number =", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberNotEqualTo(Integer value) {
            addCriterion("register_number <>", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberGreaterThan(Integer value) {
            addCriterion("register_number >", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("register_number >=", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberLessThan(Integer value) {
            addCriterion("register_number <", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberLessThanOrEqualTo(Integer value) {
            addCriterion("register_number <=", value, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberIn(List<Integer> values) {
            addCriterion("register_number in", values, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberNotIn(List<Integer> values) {
            addCriterion("register_number not in", values, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberBetween(Integer value1, Integer value2) {
            addCriterion("register_number between", value1, value2, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andRegisterNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("register_number not between", value1, value2, "registerNumber");
            return (Criteria) this;
        }

        public Criteria andBusLineIsNull() {
            addCriterion("bus_line is null");
            return (Criteria) this;
        }

        public Criteria andBusLineIsNotNull() {
            addCriterion("bus_line is not null");
            return (Criteria) this;
        }

        public Criteria andBusLineEqualTo(String value) {
            addCriterion("bus_line =", value, "busLine");
            return (Criteria) this;
        }

        public Criteria andBusLineNotEqualTo(String value) {
            addCriterion("bus_line <>", value, "busLine");
            return (Criteria) this;
        }

        public Criteria andBusLineGreaterThan(String value) {
            addCriterion("bus_line >", value, "busLine");
            return (Criteria) this;
        }

        public Criteria andBusLineGreaterThanOrEqualTo(String value) {
            addCriterion("bus_line >=", value, "busLine");
            return (Criteria) this;
        }

        public Criteria andBusLineLessThan(String value) {
            addCriterion("bus_line <", value, "busLine");
            return (Criteria) this;
        }

        public Criteria andBusLineLessThanOrEqualTo(String value) {
            addCriterion("bus_line <=", value, "busLine");
            return (Criteria) this;
        }

        public Criteria andBusLineLike(String value) {
            addCriterion("bus_line like", value, "busLine");
            return (Criteria) this;
        }

        public Criteria andBusLineNotLike(String value) {
            addCriterion("bus_line not like", value, "busLine");
            return (Criteria) this;
        }

        public Criteria andBusLineIn(List<String> values) {
            addCriterion("bus_line in", values, "busLine");
            return (Criteria) this;
        }

        public Criteria andBusLineNotIn(List<String> values) {
            addCriterion("bus_line not in", values, "busLine");
            return (Criteria) this;
        }

        public Criteria andBusLineBetween(String value1, String value2) {
            addCriterion("bus_line between", value1, value2, "busLine");
            return (Criteria) this;
        }

        public Criteria andBusLineNotBetween(String value1, String value2) {
            addCriterion("bus_line not between", value1, value2, "busLine");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementIsNull() {
            addCriterion("practice_arrangement is null");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementIsNotNull() {
            addCriterion("practice_arrangement is not null");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementEqualTo(String value) {
            addCriterion("practice_arrangement =", value, "practiceArrangement");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementNotEqualTo(String value) {
            addCriterion("practice_arrangement <>", value, "practiceArrangement");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementGreaterThan(String value) {
            addCriterion("practice_arrangement >", value, "practiceArrangement");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementGreaterThanOrEqualTo(String value) {
            addCriterion("practice_arrangement >=", value, "practiceArrangement");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementLessThan(String value) {
            addCriterion("practice_arrangement <", value, "practiceArrangement");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementLessThanOrEqualTo(String value) {
            addCriterion("practice_arrangement <=", value, "practiceArrangement");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementLike(String value) {
            addCriterion("practice_arrangement like", value, "practiceArrangement");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementNotLike(String value) {
            addCriterion("practice_arrangement not like", value, "practiceArrangement");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementIn(List<String> values) {
            addCriterion("practice_arrangement in", values, "practiceArrangement");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementNotIn(List<String> values) {
            addCriterion("practice_arrangement not in", values, "practiceArrangement");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementBetween(String value1, String value2) {
            addCriterion("practice_arrangement between", value1, value2, "practiceArrangement");
            return (Criteria) this;
        }

        public Criteria andPracticeArrangementNotBetween(String value1, String value2) {
            addCriterion("practice_arrangement not between", value1, value2, "practiceArrangement");
            return (Criteria) this;
        }

        public Criteria andCarNumberIsNull() {
            addCriterion("car_number is null");
            return (Criteria) this;
        }

        public Criteria andCarNumberIsNotNull() {
            addCriterion("car_number is not null");
            return (Criteria) this;
        }

        public Criteria andCarNumberEqualTo(Integer value) {
            addCriterion("car_number =", value, "carNumber");
            return (Criteria) this;
        }

        public Criteria andCarNumberNotEqualTo(Integer value) {
            addCriterion("car_number <>", value, "carNumber");
            return (Criteria) this;
        }

        public Criteria andCarNumberGreaterThan(Integer value) {
            addCriterion("car_number >", value, "carNumber");
            return (Criteria) this;
        }

        public Criteria andCarNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("car_number >=", value, "carNumber");
            return (Criteria) this;
        }

        public Criteria andCarNumberLessThan(Integer value) {
            addCriterion("car_number <", value, "carNumber");
            return (Criteria) this;
        }

        public Criteria andCarNumberLessThanOrEqualTo(Integer value) {
            addCriterion("car_number <=", value, "carNumber");
            return (Criteria) this;
        }

        public Criteria andCarNumberIn(List<Integer> values) {
            addCriterion("car_number in", values, "carNumber");
            return (Criteria) this;
        }

        public Criteria andCarNumberNotIn(List<Integer> values) {
            addCriterion("car_number not in", values, "carNumber");
            return (Criteria) this;
        }

        public Criteria andCarNumberBetween(Integer value1, Integer value2) {
            addCriterion("car_number between", value1, value2, "carNumber");
            return (Criteria) this;
        }

        public Criteria andCarNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("car_number not between", value1, value2, "carNumber");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andLocationNumberIsNull() {
            addCriterion("location_number is null");
            return (Criteria) this;
        }

        public Criteria andLocationNumberIsNotNull() {
            addCriterion("location_number is not null");
            return (Criteria) this;
        }

        public Criteria andLocationNumberEqualTo(Integer value) {
            addCriterion("location_number =", value, "locationNumber");
            return (Criteria) this;
        }

        public Criteria andLocationNumberNotEqualTo(Integer value) {
            addCriterion("location_number <>", value, "locationNumber");
            return (Criteria) this;
        }

        public Criteria andLocationNumberGreaterThan(Integer value) {
            addCriterion("location_number >", value, "locationNumber");
            return (Criteria) this;
        }

        public Criteria andLocationNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("location_number >=", value, "locationNumber");
            return (Criteria) this;
        }

        public Criteria andLocationNumberLessThan(Integer value) {
            addCriterion("location_number <", value, "locationNumber");
            return (Criteria) this;
        }

        public Criteria andLocationNumberLessThanOrEqualTo(Integer value) {
            addCriterion("location_number <=", value, "locationNumber");
            return (Criteria) this;
        }

        public Criteria andLocationNumberIn(List<Integer> values) {
            addCriterion("location_number in", values, "locationNumber");
            return (Criteria) this;
        }

        public Criteria andLocationNumberNotIn(List<Integer> values) {
            addCriterion("location_number not in", values, "locationNumber");
            return (Criteria) this;
        }

        public Criteria andLocationNumberBetween(Integer value1, Integer value2) {
            addCriterion("location_number between", value1, value2, "locationNumber");
            return (Criteria) this;
        }

        public Criteria andLocationNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("location_number not between", value1, value2, "locationNumber");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Integer value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Integer value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Integer value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Integer value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Integer value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Integer> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Integer> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Integer value1, Integer value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table driving_school
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table driving_school
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}