package com.happydriving.rockets.server.entity;

import java.util.Date;

public class DsPotentialStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.SERVICE_CITY_ID
     *
     * @mbggenerated
     */
    private String serviceCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.RECORD_DATE
     *
     * @mbggenerated
     */
    private Date recordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.INFO_CHANNEL
     *
     * @mbggenerated
     */
    private String infoChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.CONSULTANT_ID
     *
     * @mbggenerated
     */
    private String consultantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.REFERRER_ID
     *
     * @mbggenerated
     */
    private String referrerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.PUSHER_ID
     *
     * @mbggenerated
     */
    private String pusherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.COMMENT
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.NEXT_VISIT_DATE
     *
     * @mbggenerated
     */
    private Date nextVisitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.IS_SIGNUP
     *
     * @mbggenerated
     */
    private String isSignup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.IS_INDIRECT
     *
     * @mbggenerated
     */
    private String isIndirect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.LAST_UPDATED_STAMP
     *
     * @mbggenerated
     */
    private Date lastUpdatedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.LAST_UPDATED_TX_STAMP
     *
     * @mbggenerated
     */
    private Date lastUpdatedTxStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.CREATED_STAMP
     *
     * @mbggenerated
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.CREATED_TX_STAMP
     *
     * @mbggenerated
     */
    private Date createdTxStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_potential_student.STUDENT_FOLLOW
     *
     * @mbggenerated
     */
    private String studentFollow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.ID
     *
     * @return the value of ds_potential_student.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.ID
     *
     * @param id the value for ds_potential_student.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.SERVICE_CITY_ID
     *
     * @return the value of ds_potential_student.SERVICE_CITY_ID
     *
     * @mbggenerated
     */
    public String getServiceCityId() {
        return serviceCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.SERVICE_CITY_ID
     *
     * @param serviceCityId the value for ds_potential_student.SERVICE_CITY_ID
     *
     * @mbggenerated
     */
    public void setServiceCityId(String serviceCityId) {
        this.serviceCityId = serviceCityId == null ? null : serviceCityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.RECORD_DATE
     *
     * @return the value of ds_potential_student.RECORD_DATE
     *
     * @mbggenerated
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.RECORD_DATE
     *
     * @param recordDate the value for ds_potential_student.RECORD_DATE
     *
     * @mbggenerated
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.INFO_CHANNEL
     *
     * @return the value of ds_potential_student.INFO_CHANNEL
     *
     * @mbggenerated
     */
    public String getInfoChannel() {
        return infoChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.INFO_CHANNEL
     *
     * @param infoChannel the value for ds_potential_student.INFO_CHANNEL
     *
     * @mbggenerated
     */
    public void setInfoChannel(String infoChannel) {
        this.infoChannel = infoChannel == null ? null : infoChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.NAME
     *
     * @return the value of ds_potential_student.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.NAME
     *
     * @param name the value for ds_potential_student.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.PHONE
     *
     * @return the value of ds_potential_student.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.PHONE
     *
     * @param phone the value for ds_potential_student.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.ADDRESS
     *
     * @return the value of ds_potential_student.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.ADDRESS
     *
     * @param address the value for ds_potential_student.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.CONSULTANT_ID
     *
     * @return the value of ds_potential_student.CONSULTANT_ID
     *
     * @mbggenerated
     */
    public String getConsultantId() {
        return consultantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.CONSULTANT_ID
     *
     * @param consultantId the value for ds_potential_student.CONSULTANT_ID
     *
     * @mbggenerated
     */
    public void setConsultantId(String consultantId) {
        this.consultantId = consultantId == null ? null : consultantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.REFERRER_ID
     *
     * @return the value of ds_potential_student.REFERRER_ID
     *
     * @mbggenerated
     */
    public String getReferrerId() {
        return referrerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.REFERRER_ID
     *
     * @param referrerId the value for ds_potential_student.REFERRER_ID
     *
     * @mbggenerated
     */
    public void setReferrerId(String referrerId) {
        this.referrerId = referrerId == null ? null : referrerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.PUSHER_ID
     *
     * @return the value of ds_potential_student.PUSHER_ID
     *
     * @mbggenerated
     */
    public String getPusherId() {
        return pusherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.PUSHER_ID
     *
     * @param pusherId the value for ds_potential_student.PUSHER_ID
     *
     * @mbggenerated
     */
    public void setPusherId(String pusherId) {
        this.pusherId = pusherId == null ? null : pusherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.COMMENT
     *
     * @return the value of ds_potential_student.COMMENT
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.COMMENT
     *
     * @param comment the value for ds_potential_student.COMMENT
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.NEXT_VISIT_DATE
     *
     * @return the value of ds_potential_student.NEXT_VISIT_DATE
     *
     * @mbggenerated
     */
    public Date getNextVisitDate() {
        return nextVisitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.NEXT_VISIT_DATE
     *
     * @param nextVisitDate the value for ds_potential_student.NEXT_VISIT_DATE
     *
     * @mbggenerated
     */
    public void setNextVisitDate(Date nextVisitDate) {
        this.nextVisitDate = nextVisitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.IS_SIGNUP
     *
     * @return the value of ds_potential_student.IS_SIGNUP
     *
     * @mbggenerated
     */
    public String getIsSignup() {
        return isSignup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.IS_SIGNUP
     *
     * @param isSignup the value for ds_potential_student.IS_SIGNUP
     *
     * @mbggenerated
     */
    public void setIsSignup(String isSignup) {
        this.isSignup = isSignup == null ? null : isSignup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.IS_INDIRECT
     *
     * @return the value of ds_potential_student.IS_INDIRECT
     *
     * @mbggenerated
     */
    public String getIsIndirect() {
        return isIndirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.IS_INDIRECT
     *
     * @param isIndirect the value for ds_potential_student.IS_INDIRECT
     *
     * @mbggenerated
     */
    public void setIsIndirect(String isIndirect) {
        this.isIndirect = isIndirect == null ? null : isIndirect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.LAST_UPDATED_STAMP
     *
     * @return the value of ds_potential_student.LAST_UPDATED_STAMP
     *
     * @mbggenerated
     */
    public Date getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.LAST_UPDATED_STAMP
     *
     * @param lastUpdatedStamp the value for ds_potential_student.LAST_UPDATED_STAMP
     *
     * @mbggenerated
     */
    public void setLastUpdatedStamp(Date lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.LAST_UPDATED_TX_STAMP
     *
     * @return the value of ds_potential_student.LAST_UPDATED_TX_STAMP
     *
     * @mbggenerated
     */
    public Date getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.LAST_UPDATED_TX_STAMP
     *
     * @param lastUpdatedTxStamp the value for ds_potential_student.LAST_UPDATED_TX_STAMP
     *
     * @mbggenerated
     */
    public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.CREATED_STAMP
     *
     * @return the value of ds_potential_student.CREATED_STAMP
     *
     * @mbggenerated
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.CREATED_STAMP
     *
     * @param createdStamp the value for ds_potential_student.CREATED_STAMP
     *
     * @mbggenerated
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.CREATED_TX_STAMP
     *
     * @return the value of ds_potential_student.CREATED_TX_STAMP
     *
     * @mbggenerated
     */
    public Date getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.CREATED_TX_STAMP
     *
     * @param createdTxStamp the value for ds_potential_student.CREATED_TX_STAMP
     *
     * @mbggenerated
     */
    public void setCreatedTxStamp(Date createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_potential_student.STUDENT_FOLLOW
     *
     * @return the value of ds_potential_student.STUDENT_FOLLOW
     *
     * @mbggenerated
     */
    public String getStudentFollow() {
        return studentFollow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_potential_student.STUDENT_FOLLOW
     *
     * @param studentFollow the value for ds_potential_student.STUDENT_FOLLOW
     *
     * @mbggenerated
     */
    public void setStudentFollow(String studentFollow) {
        this.studentFollow = studentFollow == null ? null : studentFollow.trim();
    }
}