package com.happydriving.rockets.server.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DsTrainingSchedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.TRAINING_CITY
     *
     * @mbggenerated
     */
    private String trainingCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.TRAINING_DATE
     *
     * @mbggenerated
     */
    private Date trainingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.TRAINING_TIME
     *
     * @mbggenerated
     */
    private String trainingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.TRAINING_COURSE
     *
     * @mbggenerated
     */
    private String trainingCourse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.coach_id
     *
     * @mbggenerated
     */
    private String coachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.TRAINING_COUNT
     *
     * @mbggenerated
     */
    private BigDecimal trainingCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.TRAINING_DESCRIPTION
     *
     * @mbggenerated
     */
    private String trainingDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.LAST_UPDATED_STAMP
     *
     * @mbggenerated
     */
    private Date lastUpdatedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.LAST_UPDATED_TX_STAMP
     *
     * @mbggenerated
     */
    private Date lastUpdatedTxStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.CREATED_STAMP
     *
     * @mbggenerated
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.CREATED_TX_STAMP
     *
     * @mbggenerated
     */
    private Date createdTxStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_training_schedule.TRAINING_SITE_ID
     *
     * @mbggenerated
     */
    private String trainingSiteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.ID
     *
     * @return the value of ds_training_schedule.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.ID
     *
     * @param id the value for ds_training_schedule.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.TRAINING_CITY
     *
     * @return the value of ds_training_schedule.TRAINING_CITY
     *
     * @mbggenerated
     */
    public String getTrainingCity() {
        return trainingCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.TRAINING_CITY
     *
     * @param trainingCity the value for ds_training_schedule.TRAINING_CITY
     *
     * @mbggenerated
     */
    public void setTrainingCity(String trainingCity) {
        this.trainingCity = trainingCity == null ? null : trainingCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.TRAINING_DATE
     *
     * @return the value of ds_training_schedule.TRAINING_DATE
     *
     * @mbggenerated
     */
    public Date getTrainingDate() {
        return trainingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.TRAINING_DATE
     *
     * @param trainingDate the value for ds_training_schedule.TRAINING_DATE
     *
     * @mbggenerated
     */
    public void setTrainingDate(Date trainingDate) {
        this.trainingDate = trainingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.TRAINING_TIME
     *
     * @return the value of ds_training_schedule.TRAINING_TIME
     *
     * @mbggenerated
     */
    public String getTrainingTime() {
        return trainingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.TRAINING_TIME
     *
     * @param trainingTime the value for ds_training_schedule.TRAINING_TIME
     *
     * @mbggenerated
     */
    public void setTrainingTime(String trainingTime) {
        this.trainingTime = trainingTime == null ? null : trainingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.TRAINING_COURSE
     *
     * @return the value of ds_training_schedule.TRAINING_COURSE
     *
     * @mbggenerated
     */
    public String getTrainingCourse() {
        return trainingCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.TRAINING_COURSE
     *
     * @param trainingCourse the value for ds_training_schedule.TRAINING_COURSE
     *
     * @mbggenerated
     */
    public void setTrainingCourse(String trainingCourse) {
        this.trainingCourse = trainingCourse == null ? null : trainingCourse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.coach_id
     *
     * @return the value of ds_training_schedule.coach_id
     *
     * @mbggenerated
     */
    public String getCoachId() {
        return coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.coach_id
     *
     * @param coachId the value for ds_training_schedule.coach_id
     *
     * @mbggenerated
     */
    public void setCoachId(String coachId) {
        this.coachId = coachId == null ? null : coachId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.TRAINING_COUNT
     *
     * @return the value of ds_training_schedule.TRAINING_COUNT
     *
     * @mbggenerated
     */
    public BigDecimal getTrainingCount() {
        return trainingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.TRAINING_COUNT
     *
     * @param trainingCount the value for ds_training_schedule.TRAINING_COUNT
     *
     * @mbggenerated
     */
    public void setTrainingCount(BigDecimal trainingCount) {
        this.trainingCount = trainingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.TRAINING_DESCRIPTION
     *
     * @return the value of ds_training_schedule.TRAINING_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getTrainingDescription() {
        return trainingDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.TRAINING_DESCRIPTION
     *
     * @param trainingDescription the value for ds_training_schedule.TRAINING_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setTrainingDescription(String trainingDescription) {
        this.trainingDescription = trainingDescription == null ? null : trainingDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.LAST_UPDATED_STAMP
     *
     * @return the value of ds_training_schedule.LAST_UPDATED_STAMP
     *
     * @mbggenerated
     */
    public Date getLastUpdatedStamp() {
        return lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.LAST_UPDATED_STAMP
     *
     * @param lastUpdatedStamp the value for ds_training_schedule.LAST_UPDATED_STAMP
     *
     * @mbggenerated
     */
    public void setLastUpdatedStamp(Date lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.LAST_UPDATED_TX_STAMP
     *
     * @return the value of ds_training_schedule.LAST_UPDATED_TX_STAMP
     *
     * @mbggenerated
     */
    public Date getLastUpdatedTxStamp() {
        return lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.LAST_UPDATED_TX_STAMP
     *
     * @param lastUpdatedTxStamp the value for ds_training_schedule.LAST_UPDATED_TX_STAMP
     *
     * @mbggenerated
     */
    public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.CREATED_STAMP
     *
     * @return the value of ds_training_schedule.CREATED_STAMP
     *
     * @mbggenerated
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.CREATED_STAMP
     *
     * @param createdStamp the value for ds_training_schedule.CREATED_STAMP
     *
     * @mbggenerated
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.CREATED_TX_STAMP
     *
     * @return the value of ds_training_schedule.CREATED_TX_STAMP
     *
     * @mbggenerated
     */
    public Date getCreatedTxStamp() {
        return createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.CREATED_TX_STAMP
     *
     * @param createdTxStamp the value for ds_training_schedule.CREATED_TX_STAMP
     *
     * @mbggenerated
     */
    public void setCreatedTxStamp(Date createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds_training_schedule.TRAINING_SITE_ID
     *
     * @return the value of ds_training_schedule.TRAINING_SITE_ID
     *
     * @mbggenerated
     */
    public String getTrainingSiteId() {
        return trainingSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds_training_schedule.TRAINING_SITE_ID
     *
     * @param trainingSiteId the value for ds_training_schedule.TRAINING_SITE_ID
     *
     * @mbggenerated
     */
    public void setTrainingSiteId(String trainingSiteId) {
        this.trainingSiteId = trainingSiteId == null ? null : trainingSiteId.trim();
    }

    private String stringTrainingDate;

    public String getStringTrainingDate() {
        return stringTrainingDate;
    }

    public void setStringTrainingDate(String stringTrainingDate) {
        this.stringTrainingDate = stringTrainingDate;
    }

    private int isSelected;

    public int getIsSelected() {
        return isSelected;
    }

    public void setIsSelected(int isSelected) {
        this.isSelected = isSelected;
    }

    private String trainingSiteAddress;

    public String getTrainingSiteAddress() {
        return trainingSiteAddress;
    }

    public void setTrainingSiteAddress(String trainingSiteAddress) {
        this.trainingSiteAddress = trainingSiteAddress;
    }

    private String coachImgUrl;

    public String getCoachImgUrl() {
        return coachImgUrl;
    }

    public void setCoachImgUrl(String coachImgUrl) {
        this.coachImgUrl = coachImgUrl;
    }
}