package com.happydriving.rockets.server.entity;

import java.util.Date;

public class SchoolInfos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_infos.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_infos.training_area
     *
     * @mbggenerated
     */
    private String trainingArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_infos.car_type
     *
     * @mbggenerated
     */
    private String carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_infos.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_infos.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_infos.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_infos.t1
     *
     * @mbggenerated
     */
    private String t1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_infos.t2
     *
     * @mbggenerated
     */
    private String t2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_infos.t3
     *
     * @mbggenerated
     */
    private String t3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_infos.t4
     *
     * @mbggenerated
     */
    private String t4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_infos.id
     *
     * @return the value of school_infos.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_infos.id
     *
     * @param id the value for school_infos.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_infos.training_area
     *
     * @return the value of school_infos.training_area
     *
     * @mbggenerated
     */
    public String getTrainingArea() {
        return trainingArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_infos.training_area
     *
     * @param trainingArea the value for school_infos.training_area
     *
     * @mbggenerated
     */
    public void setTrainingArea(String trainingArea) {
        this.trainingArea = trainingArea == null ? null : trainingArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_infos.car_type
     *
     * @return the value of school_infos.car_type
     *
     * @mbggenerated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_infos.car_type
     *
     * @param carType the value for school_infos.car_type
     *
     * @mbggenerated
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_infos.user_id
     *
     * @return the value of school_infos.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_infos.user_id
     *
     * @param userId the value for school_infos.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_infos.created_at
     *
     * @return the value of school_infos.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_infos.created_at
     *
     * @param createdAt the value for school_infos.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_infos.updated_at
     *
     * @return the value of school_infos.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_infos.updated_at
     *
     * @param updatedAt the value for school_infos.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_infos.t1
     *
     * @return the value of school_infos.t1
     *
     * @mbggenerated
     */
    public String getT1() {
        return t1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_infos.t1
     *
     * @param t1 the value for school_infos.t1
     *
     * @mbggenerated
     */
    public void setT1(String t1) {
        this.t1 = t1 == null ? null : t1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_infos.t2
     *
     * @return the value of school_infos.t2
     *
     * @mbggenerated
     */
    public String getT2() {
        return t2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_infos.t2
     *
     * @param t2 the value for school_infos.t2
     *
     * @mbggenerated
     */
    public void setT2(String t2) {
        this.t2 = t2 == null ? null : t2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_infos.t3
     *
     * @return the value of school_infos.t3
     *
     * @mbggenerated
     */
    public String getT3() {
        return t3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_infos.t3
     *
     * @param t3 the value for school_infos.t3
     *
     * @mbggenerated
     */
    public void setT3(String t3) {
        this.t3 = t3 == null ? null : t3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_infos.t4
     *
     * @return the value of school_infos.t4
     *
     * @mbggenerated
     */
    public String getT4() {
        return t4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_infos.t4
     *
     * @param t4 the value for school_infos.t4
     *
     * @mbggenerated
     */
    public void setT4(String t4) {
        this.t4 = t4 == null ? null : t4.trim();
    }
}