package com.happydriving.rockets.server.entity;

import java.util.Date;

public class StudentSchedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_schedule.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_schedule.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_schedule.coach_schedule_id
     *
     * @mbggenerated
     */
    private Integer coachScheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_schedule.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_schedule.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_schedule.id
     *
     * @return the value of student_schedule.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_schedule.id
     *
     * @param id the value for student_schedule.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_schedule.user_id
     *
     * @return the value of student_schedule.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_schedule.user_id
     *
     * @param userId the value for student_schedule.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_schedule.coach_schedule_id
     *
     * @return the value of student_schedule.coach_schedule_id
     *
     * @mbggenerated
     */
    public Integer getCoachScheduleId() {
        return coachScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_schedule.coach_schedule_id
     *
     * @param coachScheduleId the value for student_schedule.coach_schedule_id
     *
     * @mbggenerated
     */
    public void setCoachScheduleId(Integer coachScheduleId) {
        this.coachScheduleId = coachScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_schedule.created_at
     *
     * @return the value of student_schedule.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_schedule.created_at
     *
     * @param createdAt the value for student_schedule.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_schedule.updated_at
     *
     * @return the value of student_schedule.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_schedule.updated_at
     *
     * @param updatedAt the value for student_schedule.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}