package com.happydriving.rockets.server.entity;

import java.util.Date;

public class StudentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.urgent_name
     *
     * @mbggenerated
     */
    private String urgentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.urgent_phone
     *
     * @mbggenerated
     */
    private String urgentPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.banji_id
     *
     * @mbggenerated
     */
    private Integer banjiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.chexing_id
     *
     * @mbggenerated
     */
    private Integer chexingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.shenhe
     *
     * @mbggenerated
     */
    private String shenhe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.t1
     *
     * @mbggenerated
     */
    private String t1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.t2
     *
     * @mbggenerated
     */
    private String t2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.t3
     *
     * @mbggenerated
     */
    private String t3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.t4
     *
     * @mbggenerated
     */
    private String t4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.photo
     *
     * @mbggenerated
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.shenfenzheng
     *
     * @mbggenerated
     */
    private String shenfenzheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    private int userId;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.urgent_name
     *
     * @return the value of student.urgent_name
     *
     * @mbggenerated
     */
    public String getUrgentName() {
        return urgentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.urgent_name
     *
     * @param urgentName the value for student.urgent_name
     *
     * @mbggenerated
     */
    public void setUrgentName(String urgentName) {
        this.urgentName = urgentName == null ? null : urgentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.urgent_phone
     *
     * @return the value of student.urgent_phone
     *
     * @mbggenerated
     */
    public String getUrgentPhone() {
        return urgentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.urgent_phone
     *
     * @param urgentPhone the value for student.urgent_phone
     *
     * @mbggenerated
     */
    public void setUrgentPhone(String urgentPhone) {
        this.urgentPhone = urgentPhone == null ? null : urgentPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.address
     *
     * @return the value of student.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.address
     *
     * @param address the value for student.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.banji_id
     *
     * @return the value of student.banji_id
     *
     * @mbggenerated
     */
    public Integer getBanjiId() {
        return banjiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.banji_id
     *
     * @param banjiId the value for student.banji_id
     *
     * @mbggenerated
     */
    public void setBanjiId(Integer banjiId) {
        this.banjiId = banjiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.chexing_id
     *
     * @return the value of student.chexing_id
     *
     * @mbggenerated
     */
    public Integer getChexingId() {
        return chexingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.chexing_id
     *
     * @param chexingId the value for student.chexing_id
     *
     * @mbggenerated
     */
    public void setChexingId(Integer chexingId) {
        this.chexingId = chexingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.created_at
     *
     * @return the value of student.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.created_at
     *
     * @param createdAt the value for student.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.updated_at
     *
     * @return the value of student.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.updated_at
     *
     * @param updatedAt the value for student.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.shenhe
     *
     * @return the value of student.shenhe
     *
     * @mbggenerated
     */
    public String getShenhe() {
        return shenhe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.shenhe
     *
     * @param shenhe the value for student.shenhe
     *
     * @mbggenerated
     */
    public void setShenhe(String shenhe) {
        this.shenhe = shenhe == null ? null : shenhe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.t1
     *
     * @return the value of student.t1
     *
     * @mbggenerated
     */
    public String getT1() {
        return t1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.t1
     *
     * @param t1 the value for student.t1
     *
     * @mbggenerated
     */
    public void setT1(String t1) {
        this.t1 = t1 == null ? null : t1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.t2
     *
     * @return the value of student.t2
     *
     * @mbggenerated
     */
    public String getT2() {
        return t2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.t2
     *
     * @param t2 the value for student.t2
     *
     * @mbggenerated
     */
    public void setT2(String t2) {
        this.t2 = t2 == null ? null : t2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.t3
     *
     * @return the value of student.t3
     *
     * @mbggenerated
     */
    public String getT3() {
        return t3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.t3
     *
     * @param t3 the value for student.t3
     *
     * @mbggenerated
     */
    public void setT3(String t3) {
        this.t3 = t3 == null ? null : t3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.t4
     *
     * @return the value of student.t4
     *
     * @mbggenerated
     */
    public String getT4() {
        return t4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.t4
     *
     * @param t4 the value for student.t4
     *
     * @mbggenerated
     */
    public void setT4(String t4) {
        this.t4 = t4 == null ? null : t4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.photo
     *
     * @return the value of student.photo
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.photo
     *
     * @param photo the value for student.photo
     *
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.shenfenzheng
     *
     * @return the value of student.shenfenzheng
     *
     * @mbggenerated
     */
    public String getShenfenzheng() {
        return shenfenzheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.shenfenzheng
     *
     * @param shenfenzheng the value for student.shenfenzheng
     *
     * @mbggenerated
     */
    public void setShenfenzheng(String shenfenzheng) {
        this.shenfenzheng = shenfenzheng == null ? null : shenfenzheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.product_id
     *
     * @return the value of student.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.product_id
     *
     * @param productId the value for student.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public String getPersonalitytest() {
        return personalitytest;
    }

    public void setPersonalitytest(String personalitytest) {
        this.personalitytest = personalitytest;
    }

    private String personalitytest;

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }
}