package com.happydriving.rockets.campaign.spread.entity;

import java.util.Date;

public class SpreadStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spread_student.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spread_student.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spread_student.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spread_student.referrer_id
     *
     * @mbggenerated
     */
    private Integer referrerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spread_student.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spread_student.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spread_student.transfer_at
     *
     * @mbggenerated
     */
    private Date transferAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spread_student.is_transfer
     *
     * @mbggenerated
     */
    private Boolean isTransfer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spread_student.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spread_student.id
     *
     * @return the value of spread_student.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spread_student.id
     *
     * @param id the value for spread_student.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spread_student.phone
     *
     * @return the value of spread_student.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spread_student.phone
     *
     * @param phone the value for spread_student.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spread_student.name
     *
     * @return the value of spread_student.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spread_student.name
     *
     * @param name the value for spread_student.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spread_student.referrer_id
     *
     * @return the value of spread_student.referrer_id
     *
     * @mbggenerated
     */
    public Integer getReferrerId() {
        return referrerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spread_student.referrer_id
     *
     * @param referrerId the value for spread_student.referrer_id
     *
     * @mbggenerated
     */
    public void setReferrerId(Integer referrerId) {
        this.referrerId = referrerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spread_student.comment
     *
     * @return the value of spread_student.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spread_student.comment
     *
     * @param comment the value for spread_student.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spread_student.created_at
     *
     * @return the value of spread_student.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spread_student.created_at
     *
     * @param createdAt the value for spread_student.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spread_student.transfer_at
     *
     * @return the value of spread_student.transfer_at
     *
     * @mbggenerated
     */
    public Date getTransferAt() {
        return transferAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spread_student.transfer_at
     *
     * @param transferAt the value for spread_student.transfer_at
     *
     * @mbggenerated
     */
    public void setTransferAt(Date transferAt) {
        this.transferAt = transferAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spread_student.is_transfer
     *
     * @return the value of spread_student.is_transfer
     *
     * @mbggenerated
     */
    public Boolean getIsTransfer() {
        return isTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spread_student.is_transfer
     *
     * @param isTransfer the value for spread_student.is_transfer
     *
     * @mbggenerated
     */
    public void setIsTransfer(Boolean isTransfer) {
        this.isTransfer = isTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spread_student.city_id
     *
     * @return the value of spread_student.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spread_student.city_id
     *
     * @param cityId the value for spread_student.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
}